# Generated by Django 4.1.2 on 2022-10-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_subscribed_subscribed_shop_subscr_name_2c4ae3_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribed',
            name='email',
        ),
    ]
