# Generated by Django 4.1.2 on 2022-10-21 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_subscribed_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(null=True)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date sent')),
            ],
            options={
                'ordering': ['date_sent'],
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.DeleteModel(
            name='Subscribed',
        ),
        migrations.AddIndex(
            model_name='subscribers',
            index=models.Index(fields=['email'], name='shop_subscr_email_43b10f_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['date_sent'], name='shop_mailme_date_se_663e59_idx'),
        ),
    ]
