# Generated by Django 4.1.2 on 2022-10-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_mailmessage_subscribers_delete_subscribed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailMessage',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
