# Generated by Django 4.1.2 on 2022-10-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_mailmessage_delete_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='headline',
            field=models.BooleanField(default=False),
        ),
    ]
