# Generated by Django 4.1.2 on 2022-11-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_cs',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='surname_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
