# Generated by Django 4.1.2 on 2022-11-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_person_name_cs_person_name_en_person_profession_cs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_cs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_cs',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
