# Generated by Django 4.1.2 on 2022-11-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_cz_price_product_cz_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_cs',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
