# Generated by Django 4.1.2 on 2022-11-07 19:22

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_price_cs_product_price_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cz_price_cs',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CZK', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cz_price_en',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CZK', max_digits=14, null=True),
        ),
    ]
