# Generated by Django 4.1.2 on 2022-11-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_cz_price_cs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_cs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_en',
        ),
    ]
