# Generated by Django 4.1.2 on 2022-11-07 21:51

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_product_price_cs_remove_product_price_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cz_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'CZK Kč'), ('EUR', 'EUR €')], default='CZK', editable=False, max_length=3, null=True),
        ),
    ]
