# Generated by Django 4.1.2 on 2022-11-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_cz_price_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cz_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cz_price_currency',
        ),
        migrations.AddField(
            model_name='product',
            name='eur_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
