# Generated by Django 4.1.2 on 2022-11-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_product_cz_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='eur_price',
        ),
    ]
