# Generated by Django 4.1.2 on 2022-11-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_price_cs_product_price_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_cs',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
