# Generated by Django 4.1.2 on 2022-11-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_category_name_cs_category_name_en_category_slug_cs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
