# Generated by Django 4.1.2 on 2022-11-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_cs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_en',
        ),
    ]
