# Generated by Django 4.1.2 on 2022-10-21 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(null=True)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date sent')),
            ],
            options={
                'ordering': ['date_sent'],
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AddIndex(
            model_name='subscribers',
            index=models.Index(fields=['email'], name='newsletter__email_9c0aba_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['date_sent'], name='newsletter__date_se_f0a654_idx'),
        ),
    ]
