# Generated by Django 4.1.2 on 2022-10-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_subscribers_date_alter_subscribers_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'ordering': ['date']},
        ),
    ]
