# Generated by Django 4.1.2 on 2022-12-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_first_name_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
