"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from django.core.mail import EmailMessage


DJANGO_SETTINGS_MODULE = 'web.settings.local'

#Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent #3x parent for redirecting to one folder above

# Quick-start development settings - unsuitablpe for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ###

# SECURITY WARNING: don't run with debug turned on in production!
#removed debug

#ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'payment.apps.PaymentConfig',
    'newsletter.apps.NewsletterConfig',
    'crispy_forms',
    'rosetta',
    'modeltranslation',
    'django.contrib.admin',
    'djmoney',
    'debug_toolbar',
    'celery',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', #added when pursuing internationalization
    'django.middleware.common.CommonMiddleware', 
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',

            ],
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

#removed database

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
CRISPY_TEMPLATE_PACK = 'uni_form'

LANGUAGE_CODE = 'cs'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

#generating pdf
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CART_SESSION_ID = 'cart'


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

#this is to make Django to write emails to the console

#Setting up email server FORPSI
#https://support.forpsi.com/kb/a3147/konfigurace-smtp-serveru.aspx


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.forpsi.com'
EMAIL_HOST_USER = 'zuzi@zuzikoko.com'
EMAIL_HOST_PASSWORD = '#G1445203l'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#EMAIL_ENCRYPTION='STARTTLS'
DEFAULT_FROM_EMAIL = 'zuzi@zuzikoko.com'


#outlook email configuration
'''
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.outlook.com'
EMAIL_HOST_USER = 'vlkscraper@outlook.com'
EMAIL_HOST_PASSWORD = 'wbfdyjqbrpodzufw'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_ENCRYPTION='STARTTLS'
DEFAULT_FROM_EMAIL = 'vlkscraper@outlook.com'''



#stripe settings
STRIPE_PUBLISHABLE_KEY = 'pk_test_51LjOXfLCxZuAJwiOkvsfs1C4lpXAsOGKbeAftRLHhPeaD6ImgG00a1SISD0KwFZ6tMgzSAnTLoIE0EpHJDFz2gLZ00lrF3pb7w'
STRIPE_SECRET_KEY = 'sk_test_51LjOXfLCxZuAJwiONPiwoFPRelBRyNxL074KaKfAAMAKOeU71LL7twC3dj3A9XsdsqqMuEv8tY2qR2NyhOHCFYcq00WNeRxe9T'
STRIPE_API_VERSION = '2022-08-01'

#from this link: https://dashboard.stripe.com/test/webhooks/create?endpoint_location=local
STRIPE_WEBHOOK_SECRET = 'whsec_bdc6e5fb946fe185e8e085495cbae45bbea29433778b25a70a96761d3c36ad27'


LANGUAGES = [
    ('cs', _('Česky')),
    ('en', _('English')),
]

gettext = lambda s: s
LANGUAGES = (
    ('cs', gettext('Česky')),
    ('en', gettext('English')),
)


LOCALE_PATHS = [ #these files are for Django to look for translation files
    BASE_DIR / 'locale',
]

MODELTRANSLATION_DEFAULT_LANGUAGE = 'cs'
TRANSLATION_REGISTRY = "web.translation"
MODEL_TRANSLATION_LANGUAGES = ('cs', 'en')

CURRENCIES = ('CZK', 'EUR')
CURRENCY_CHOICES = [
 ('CZK', 'CZK Kč'),
 ('EUR', 'EUR €')]

DEFAULT_CURRENCY = 'CZK'

DJANGO_MONEY_RATES = {
    'DEFAULT_BACKEND': 'djmoney_rates.backends.OpenExchangeBackend',
    'OPENEXCHANGE_URL': 'http://openexchangerates.org/api/latest.json',
    'OPENEXCHANGE_APP_ID': '33a5e7444af34ca7a032d16e7851debf',
    'OPENEXCHANGE_BASE_CURRENCY': 'EUR',
}

#INTERNAL_IPS = ['127x.0.0.1',"0.0.0.0:8000"] 

#import socket
#hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
#INTERNAL_IPS += [".".join(ip.split(".")[:-1] + ["1"]) for ip in ips]



ASGI_APPLICATION = 'web.asgi.application'
#redis https://levelup.gitconnected.com/get-redis-up-and-running-on-docker-4af011db9bc7
